on:
  pull_request:
    types: [closed]
jobs:
  create_new_branch:
    runs-on: ubuntu-latest
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Extract issue number
        shell: bash
        run: echo "::set-env name=ISSUE_NUMBER::$(echo ${BRANCH_NAME%%/*})"
        id: extract_issue_number

      - name: Move issue card to in progress
        run: |        
          curl --request POST \
            --url https://api.zenhub.com/p2/workspaces/${{ secrets.ZH_WORKSPACE_ID }}/repositories/${{ secrets.REPO_ID }}/issues/${ISSUE_NUMBER}/moves \
            --header 'X-Authentication-Token: ${{ secrets.ZH_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
                "pipeline_id": "${{ secrets.ZH_QA_ID }}",
                "position": "top"
              }'


