name: release production

on:
  # release:
  #   # Only use the types keyword to narrow down the activity types that will trigger your workflow.
  #   types: [published]
  push:
    branches:
      - 'master'

jobs:
  release_production:
    runs-on: ubuntu-latest
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Extract issue number
        shell: bash
        run: echo "::set-env name=ISSUE_NUMBER::$(echo ${BRANCH_NAME%%/*})"
        id: extract_issue_number

      - name: Move issue card to in progress
        run: |        
          curl --request POST \
            --url https://api.zenhub.com/p1/repositories/${{ secrets.REPO_ID }}/epics/${ISSUE_NUMBER}/update_issues \
            --header 'X-Authentication-Token: ${{ secrets.ZH_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
                "remove_issues": [{ "repo_id": "${{ secrets.REPO_ID }}", "issue_number": "${ISSUE_NUMBER}" }]
              }'


